---
- hosts: all
  sudo: yes
  tasks:
    - name: run echo command
      command: /bin/echo hello sammy

  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
...                 
